### ISSUE TITLE
JHOVE reporting PDF as v1.3 and as ISO PDF/A-1, Level B

### ISSUE THREAD

**Issue by pmay** [openpreserve/jhove#101]
Siegfried reports the file to be PDF v1.3 and **not** pdf/a.

JHOVE output snippet:

```
Jhove (Rel. 1.12.48, 2016-05-12)
 Date: 2016-08-08 10:09:34 BST
 RepresentationInformation: c:\Users\pmay\Downloads\281474990846918.pdf
  ReportingModule: PDF-hul, Rel. 1.7 (2012-08-12)
  LastModified: 2016-08-05 14:49:21 BST
  Size: 205146
  Format: PDF
  Version: 1.3
  Status: Well-Formed, but not valid
  SignatureMatches:
   PDF-hul
  ErrorMessage: <snip...>
  MIMEtype: application/pdf
  Profile: ISO PDF/A-1, Level B
  PDFMetadata: <snip...>
```
