### ISSUE TITLE
Very long validating process on PDF 1.4 file

### ISSUE THREAD

**Issue by alexandregranier** [openpreserve/jhove#161]
## Dev Effort
2D

## Description
This file too large to be upload here (a pdf 1.4 generated with LibreOffice 4.2) takes more than 5 minutes to be validated by Jhove (either 1.11 or 1.12.x). The file is invalid and it leads to use a lot of CPU time.
I think we often meet this issue in our archive platform.
[(https://facile.cines.fr/long.pdf)]

**Comment by RussellMcOrmond** [comment]
We have some multi-page PDF files generated by ABBYY Recognition Server that have 5+ taken hours.  I can post some samples if this is of interest.

**Comment by carlwilson** [comment]
Hi @RussellMcOrmond that would be useful, if we have some examples we can at least offer an opinion.

**Comment by RussellMcOrmond** [comment]
```
tdr@romano:~$ time /opt/jhove/jhove -k -o numeris.TV_1965_FA00_160.pdf.xml /cihmz2/repository/aip/numeris/708/numeris.TV_1965_FA00_160/data/sip/data/files/document.pdf 

real	265m5.548s
user	275m8.588s
sys	13m40.638s
tdr@romano:~$ 

```
This was done on a 24 core, 128G RAM machine that I ran few other processes on while doing this quick test.

The report included:

```
Jhove (Rel. 1.16.6, 2017-04-27)
 Date: 2017-04-28 07:56:22 EDT
 RepresentationInformation: /cihmz2/repository/aip/numeris/708/numeris.TV_1965_FA00_160/data/sip/data/files/document.pdf
  ReportingModule: PDF-hul, Rel. 1.8 (2017-03-14)
  LastModified: 2016-10-06 09:06:35 EDT
  Size: 177360349
  Format: PDF
  Version: 1.4
  Status: Well-Formed and valid
  SignatureMatches:
   PDF-hul
  InfoMessage: Too many fonts to report; some fonts omitted.: Total fonts = 1875
  MIMEtype: application/pdf
  Profile: Tagged PDF, ISO PDF/A-1, Level B

```

There is a download button for this PDF at: http://numeris.canadiana.ca/view/numeris.TV_1965_FA00_160/
(Right beside the - + for zoom).

For Numeris we had ABBYY Recognition Server generate multi-page PDF files from the scanned images.  For other projects we generated single-page PDF files from OCR and then used pdftk and poppler to generate multi-page PDF which turned out to be worse (IE: pdftk generated PDF files JHOVE would validate if the result was small enough, and poppler would generate a PDF file which JHOVE wouldn't validate -- details were in the mailing list).

I'm not sure if this is the same problem Alexandre found, but it might be related.
