### ISSUE TITLE
PDF regression test file exhibits error in JHOVE 1.16.5

### ISSUE THREAD

**Issue by david-russo** [openpreserve/jhove#255]
## Dev Effort
0.5D

## Description
[The file](https://github.com/openpreserve/jhove/blob/integration/test-root/corpora/regression/modules/PDF-hul/pdf-hul-40-govdocs-088919.pdf) might instead be more appropriate as an error example:
```
Jhove (Rel. 1.16.5, 2017-03-20)
 Date: 2017-05-19 10:58:36 BST
 RepresentationInformation: pdf-hul-40-govdocs-088919.pdf
  ReportingModule: PDF-hul, Rel. 1.8 (2017-03-14)
  LastModified: 2017-03-21 12:11:06 GMT
  Size: 1079469
  Format: PDF
  Version: 1.5
  Status: Well-Formed, but not valid
  SignatureMatches:
   PDF-hul
  ErrorMessage: Invalid outline dictionary item
   Offset: 295
  MIMEtype: application/pdf
```
