### ISSUE TITLE
Possible issue with ColorSpace

### ISSUE THREAD

**Issue by RussellMcOrmond** [openpreserve/jhove#297]
## Dev Effort
2D

## Description
We have some CMYK which aren't differentiated in the JHOVE 1.16.5 reports.  I'm wondering if this is a problem in the software, or that I'm not using the tool correctly.

Using ImageMagick's identify it notices the differences between a lone CMYK image and Greyscale images.

Jhove indicated YCbCr for all of them.

```
cihm@quark:/opt/wip/Temp/export/oop_issues/oop.debates_HOC0104_01-sip/data/files$ identify -verbose -format "%f %[colorspace]\n" 000?.jpg 
0001.jpg CMYK
0002.jpg Gray
0003.jpg Gray
0004.jpg Gray
0005.jpg Gray
0006.jpg Gray
0007.jpg Gray
0008.jpg Gray
0009.jpg Gray

cihm@quark:/opt/wip/Temp/export/oop_issues/oop.debates_HOC0104_01-sip/data/files$ /opt/jhove/jhove 000?.jpg | grep ColorSpace
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
      ColorSpace: YCbCr
cihm@quark:/opt/wip/Temp/export/oop_issues/oop.debates_HOC0104_01-sip/data/files$ /opt/jhove/jhove -v
Jhove (Rel. 1.16.5, 2017-03-20)
 Date: 2017-11-27 16:38:57 EST
 App:
  API: 1.16.5, 2017-03-20
  Configuration: /opt/jhove/conf/jhove.conf
  JhoveHome: /opt/jhove
  Encoding: utf-8
  TempDirectory: /tmp
  BufferSize: 131072
  Module: AIFF-hul 1.3
  Module: ASCII-hul 1.3
  Module: BYTESTREAM 1.3
  Module: GIF-hul 1.3
  Module: GZIP-kb 0.1
  Module: HTML-hul 1.3
  Module: JPEG-hul 1.2
  Module: JPEG2000-hul 1.3
  Module: PDF-hul 1.8
  Module: PNG-gdm 1.0
  Module: TIFF-hul 1.7
  Module: UTF8-hul 1.6
  Module: WARC-kb 1.0
  Module: WAVE-hul 1.4
  Module: XML-hul 1.4
  OutputHandler: Audit 1.1
  OutputHandler: TEXT 1.5
  OutputHandler: XML 1.7
  Usage: java JHOVE [-c config] [-m module] [-h handler] [-e encoding] [-H handler] [-o output] [-x saxclass] [-t tempdir] [-b bufsize] [-l loglevel] [[-krs] dir-file-or-uri [...]]
  Rights: Derived from software Copyright 2004-2011 by the President and Fellows of Harvard College. Version 1.7 to 1.11 independently released. Version 1.12 onwards released by Open Preservation Foundation. Released under the GNU Lesser General Public License.
cihm@quark:/opt/wip/Temp/export/oop_issues/oop.debates_HOC0104_01-sip/data/files$ 

```

I noticed this issue when trying to confirm image differences in the context of https://github.com/medusa-project/cantaloupe/issues/177
