### ISSUE TITLE
XML that is well-formed according to xmllint reported as "Not well-formed" by JHOVE

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jhove#310]
## Dev Effort
1D - investigation

## Description
Look at the following METS file:

[mets-test.xml](https://gist.github.com/bitsgalore/15f54369ba99233316976b758be452c2)

According to xmllint (v. 20904) it contains well-formed XML:

    xmllint --noout mets-test.xml

Result: no error messages (which means it is well-formed)

Next I try to validate the same file with JHOVE (v. 1.18.1):

    jhove -m XML-hul met-tests.xml

Result:

    Jhove (Rel. 1.18.1, 2017-11-30)
     Date: 2018-02-22 12:53:55 CET
     RepresentationInformation: mets-test.xml
      ReportingModule: XML-hul, Rel. 1.4 (2007-01-08)
      LastModified: 2018-02-21 17:31:20 CET
      Size: 106387
      Format: XML
      Status: Not well-formed
      SignatureMatches:
       XML-hul
      ErrorMessage: XML document structures must start and end within the same entity.: Line = 1, Column = 97
      MIMEtype: text/xml

So according to JHOVE the file is not well-formed! The error message is even more puzzling, as the position corresponds to a namespace definition.

The strangest thing of all is that some XML documents that would pass a "well-formed" by JHOVE only yesterday suddenly give me the above error today! I initially suspected something weird going on in my JHOVE configuration, but after uninstalling + reinstalling JHOVE + checking on 2 different machines (Windows + Linux machine) I keep getting the above error for several XML documents that somehow passed well-formedness checks earlier on. Or am I overlooking something obvious here?

**Comment by anjackson** [comment]
Just to make things more confusing, I downloaded it and it works fine for me!

```
Jhove (Rel. 1.14.0, 2016-10-06)
 Date: 2018-02-22 12:49:27 GMT
 RepresentationInformation: /Users/andy/Downloads/mets-test.xml
  ReportingModule: UTF8-hul, Rel. 1.6 (2014-07-18)
  LastModified: 2018-02-22 12:49:17 GMT
  Size: 106387
  Format: UTF-8
  Status: Well-Formed and valid
  MIMEtype: text/plain; charset=UTF-8
  UTF8Metadata: 
   Characters: 106386
   UnicodeBlocks: Basic Latin, Latin-1 Supplement
   LineEndings: LF
```

But note that's JHOVE 1.14.6 (from Homebrew).

Is the real problem the fact that it's failing to download the XSDs? e.g. because it's not picked up the proxy?
