### ISSUE TITLE
headless installation

### ISSUE THREAD

**Issue by lsh-0** [openpreserve/jhove#335]
## Dev Effort
2D

## Description
running `java -jar jhove-latest.jar` flashes something on the screen and then displays a single white pixel. Killing this I get the prompt "this will cancel the installation".

running `java -jar jhove-latest.jsr -m PDF-hul <pdffile>` gives me the errors:

```
Logging initialized at level 'INFO'
Commandline arguments: -m PDF-hul <pdffile>
Detected platform: linux,version=4.16.4-1-ARCH,arch=x64,symbolicName=null,javaVersion=1.8.0_172
ERROR:  'Content is not allowed in prolog.'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Content is not allowed in prolog.'
```

I would assume I get the above because it needs to write a config file or something that typically happens during installation. Is it possible to install jhove headless?

**Comment by carlwilson** [comment]
Hi @08robertsj 

Headless installation is possible, see a bash script example from the [test scripts here](https://github.com/openpreserve/jhove/blob/integration/jhove-bbt/scripts/inc/bb-utils.sh#L82). It uses [this configuration file](https://github.com/openpreserve/jhove/blob/integration/jhove-bbt/scripts/auto-vagrant-install.xml). Get in touch if you have any issues at all.

Thanks.

**Comment by def-fun** [comment]
A guide for people who is try to install jhove on linux server without GUI(headless), based on @carlwilson 's comment :

```shell
wget http://software.openpreservation.org/rel/jhove-latest.jar
wget https://github.com/openpreserve/jhove/raw/integration/jhove-bbt/scripts/auto-vagrant-install.xml
# apt/yum/pacman install openjdk-8-jre-headless 
sed -i "s%^<installpath>.*%<installpath>${HOME}/.jhove</installpath>%" auto-vagrant-install.xml
java -jar jhove-latest.jar auto-vagrant-install.xml
```

then jhove was installed to `${HOME}/.jhove`.  To make jhove is available in shell, you can

```shell
sudo ln -s ~/.jhove/jhove /usr/local/bin/jhove
```
finally test jhove:
```
# jhove
Jhove (Rel. 1.26.1, 2022-07-14)
 Date: 2023-01-20 00:39:40 EST
 App:
  API: 1.26.1, 2022-07-14
  Configuration: /home/btx/.jhove/conf/jhove.conf
  JhoveHome: /home/btx/.jhove
  Encoding: utf-8
  TempDirectory: /tmp
  BufferSize: 131072
  Module: AIFF-hul 1.6.2
  Module: ASCII-hul 1.4.2
  Module: BYTESTREAM 1.4
  Module: EPUB-ptc 1.1
  Module: GIF-hul 1.4.3
  Module: GZIP-kb 0.2
  Module: HTML-hul 1.4.2
  Module: JPEG-hul 1.5.3
  Module: JPEG2000-hul 1.4.3
  Module: PDF-hul 1.12.3
  Module: PNG-gdm 1.1
  Module: TIFF-hul 1.9.3
  Module: UTF8-hul 1.7.2
  Module: WARC-kb 1.1
  Module: WAVE-hul 1.8.2
  Module: XML-hul 1.5.2
  OutputHandler: Audit 1.1
  OutputHandler: JSON 1.1
  OutputHandler: TEXT 1.6
  OutputHandler: XML 1.9
  Usage: java JHOVE [-c config] [-m module] [-h handler] [-e encoding] [-H handler] [-o output] [-x saxclass] [-t tempdir] [-b bufsize] [-l loglevel] [[-krs] dir-file-or-uri [...]]
  Rights: Derived from software Copyright 2004-2011 by the President and Fellows of Harvard College. Version 1.7 to 1.11 independently released. Version 1.12 onwards released by Open Preservation Foundation. Released under the GNU Lesser General Public License.

# jhove /var/log/auth.log
Jhove (Rel. 1.26.1, 2022-07-14)
 Date: 2023-01-20 04:37:46 UTC
 RepresentationInformation: /var/log/auth.log
  ReportingModule: UTF8-hul, Rel. 1.7.2 (2022-04-22)
  LastModified: 2023-01-20 04:17:01 UTC
  Size: 71844
  Format: UTF-8
  Status: Well-Formed and valid
  MIMEtype: text/plain; charset=UTF-8
  UTF8Metadata: 
   Characters: 71666
   UnicodeBlocks: Basic Latin, CJK Unified Ideographs
   LineEndings: LF

# jhove  a.pdf
Jhove (Rel. 1.26.1, 2022-07-14)
 Date: 2023-01-20 04:29:21 UTC
 RepresentationInformation: a.pdf
  ReportingModule: BYTESTREAM, Rel. 1.4 (2018-10-01)
  LastModified: 2023-01-20 04:29:04 UTC
  Size: 4273970
  Format: bytestream
  Status: Well-Formed and valid
  SignatureMatches:
   PDF-hul
  MIMEtype: application/octet-stream
```
