### ISSUE TITLE
Message IDs not clearly associated to message contents in text reports

### ISSUE THREAD

**Issue by david-russo** [openpreserve/jhove#453]
In the below example the "ID" properties appear on a level equal to their governing InfoMessages instead of clearly belonging to them like their "Offset" properties. This could cause ambiguity when one or more of the messages does not have an identifier, and add complexity to any software intending to parse the reports.

```
Jhove (Rel. 1.22.1, 2019-04-17)
 Date: 2019-04-23 11:04:48 BST
 RepresentationInformation: test-ignored-final-chunk-truncated.wav
  ReportingModule: WAVE-hul, Rel. 1.7.1 (2019-04-17)
  LastModified: 2018-02-28 16:21:35 GMT
  Size: 56
  Format: WAVE
  Status: Not well-formed
  SignatureMatches:
   WAVE-hul
  ID: WAVE-HUL-7
  InfoMessage: Ignored unrecognized chunk: PAD
   Offset: 54
  ID: WAVE-HUL-3
  ErrorMessage: Unexpected end of file: Bytes missing = 3; Truncated chunk = PAD
   Offset: 56
  MIMEtype: audio/vnd.wave; codec=1
  Profile: PCMWAVEFORMAT
  ...
```
