### ISSUE TITLE
Invalid ICCProfile in APP2 segment

### ISSUE THREAD

**Issue by thorsted** [openpreserve/jhove#554]
We have been seeing this ErrorMessage even though the JPG is reported back as Well-Formed & Valid. Seems to be related to the newer iPhone "Display P3" ICC Profile.
![IMG_2639](https://user-images.githubusercontent.com/213296/70659853-272bcd00-1c1e-11ea-87af-880d492f4810.JPG)

```
  ReportingModule: JPEG-hul, Rel. 1.5.2 (2019-11-05)
  LastModified: 2019-12-04 16:05:57 MST
  Size: 3780466
  Format: JPEG
  Status: Well-Formed and valid
  SignatureMatches:
   JPEG-hul
  ErrorMessage: Unknown GPSInfo IFD tag: Tag = 31;
   ID: TIFF-HUL-17
   Offset: 2260
  ErrorMessage: "Invalid ICCProfile in APP2 segment; message : No description in ICC profile v4
   ID: JPEG-HUL-11
   Offset: 578
```
