### ISSUE TITLE
PNG-Module throws NullPointerException

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#694]
We have a few pngs that throw java.lang NullPointerExceptions during validation. I'm attaching an example.  It would be great if someone could investigate.

The file valides fines with exiftool and pngchecker

![ijslogo](https://user-images.githubusercontent.com/13165865/138871556-90bcb08a-a42c-47d9-a99a-86855bc1a2f5.png)
.

**Comment by karenhanson** [comment]
This sounded familiar so I checked... it appears to be a duplicate of issue #148, which was fixed as part of the last hackathon. The fix is merged to the `integration` branch but has not yet been released. To double check, I installed the latest release (1.24) and this is what I got:
```
Jhove (Rel. 1.24.0, 2021-11-10)
 Date: 2021-11-10 16:11:50 EST
 RepresentationInformation: ./138871556-90bcb08a-a42c-47d9-a99a-86855bc1a2f5.png
  ReportingModule: PNG-gdm, Rel. 1.0 (2016-02-25)
  LastModified: 2021-11-10 15:56:49 EST
  Size: 6459
  Format: PNG
  Status: Not well-formed
  ErrorMessage: Exception java.lang.NullPointerException
  MIMEtype: image/png
```
I then built from the `integration` branch (1.25.0-SNAPSHOT) and the error is gone:
```
Jhove (Rel. 1.25.0-SNAPSHOT, 2021-11-10)
 Date: 2021-11-10 16:12:07 EST
 RepresentationInformation: ./138871556-90bcb08a-a42c-47d9-a99a-86855bc1a2f5.png
  ReportingModule: PNG-gdm, Rel. 1.0 (2016-02-25)
  LastModified: 2021-11-10 15:56:49 EST
  Size: 6459
  Format: PNG
  Status: Well-Formed and valid
  MIMEtype: image/png
  PNGMetadata:
   NisoImageMetadata:
    ImageWidth: 131
    ImageHeight: 40
    ColorSpace: RGB
    BitsPerSample: 8
    BitsPerSampleUnit: integer
   ColorType: Truecolour
   Compression: Deflate
   Filter type: 0
   Interlace: None
   Keywords:
    Keyword:
     Key: Software
     Value: Adobe ImageReady
    Keyword:
     Key: XML:com.adobe.xmp
     Value: <?xpacket begin="├»┬╗┬┐" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.0-c061 64.140949, 2010/12/07-10:57:01        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#" xmp:CreatorTool="Adobe Photoshop CS5.1 Windows" xmpMM:InstanceID="xmp.iid:C5768F888D8611E3B1EFF59598BC4927" xmpMM:DocumentID="xmp.did:C5768F898D8611E3B1EFF59598BC4927"> <xmpMM:DerivedFrom stRef:instanceID="xmp.iid:C5768F868D8611E3B1EFF59598BC4927" stRef:documentID="xmp.did:C5768F878D8611E3B1EFF59598BC4927"/> </rdf:Description> </rdf:RDF> </x:xmpmeta> <?xpacket end="r"?>
     Language:
     Translated key:
```
