### ISSUE TITLE
Jhove misidentifies certain plain text files as AIFF files

### ISSUE THREAD

**Issue by sprater** [openpreserve/jhove#902]
Jhove will identify plain text files that start with the word "FORM" as well-formed AIFF files.

```
./jhove -s ./misidentified-text.txt

Jhove (Rel. 1.28.0, 2023-05-18)
 Date: 2024-02-23 16:50:36 CST
 RepresentationInformation: ./misidentified-text.txt
  ReportingModule: AIFF-hul, Rel. 1.6.2 (2022-04-22)
  LastModified: 2024-02-23 11:31:30 CST
  Size: 1701
  Format: AIFF
  Status: Well-Formed
  SignatureMatches:
   AIFF-hul
  MIMEtype: audio/x-aiff
  ```
  Attached is a sample plain text document that can be used to reproduce the error.
  
[misidentified-text.txt](https://github.com/openpreserve/jhove/files/14390722/misidentified-text.txt)
